<ContentNavigationDrawer>:

    ScrollView:

        MDList:

            OneLineListItem:
                text: "Screen 1"
                on_press:
                    # root.nav_drawer.set_state("close")
                    # root.screen_manager.current = "scr 1"

            OneLineListItem:
                text: "Screen 2"
                on_press:
                    # root.nav_drawer.set_state("close")
                    # root.screen_manager.current = "scr 2"